## [FER2013](https://www.kaggle.com/c/challenges-in-representation-learning-facial-expression-recognition-challenge/data) data preparation 

CSV file downloaded from Kaggle are processed and saved to different folders depending on Training, PublicTest, and PrivateTest folders categories.

Each folders has all the categories like (Angry, Sad, Fear, Surprise, Happy, Neutral, Disgust).

Training, Validation and Test folder are zipped and stored in google drive

This notebook prepares data to be readily useful in Colab for later use. 

In [ ]:
# Connecting the google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# Checking the current directory contents
!ls

drive  sample_data


In [ ]:
# Checking the present working directory path
!pwd

/content


In [ ]:
# Reading the downloaded CSV file using numpy
import os
import numpy as np

"""
    0 = Angry, 
    1 = Disgust, 
    2 = Fear, 
    3 = Happy,
    4 = Sad,
    5 = Surprise,
    6 = Neutral
"""
label_dictionary = {
    0 : "Angry",
    1 : "Disgust",
    2 : "Fear", 
    3 : "Happy",
    4 : "Sad",
    5 : "Surprise",
    6 : "Neutral"
}
label_names = ['Angry', 'Disgust', 'Fear', 'Happy', 'Sad', 'Surprise', 'Neutral']

# dataset path og google drive
dataset_path = "/content/drive/My Drive/ENGR635-Deep Learning System Design Project/Dataset/fer2013/fer2013.csv" 
data = np.genfromtxt(dataset_path, delimiter=',',dtype=None, encoding='utf8')
print(data.shape)

(35888, 3)


In [ ]:
# Header
data[0] 

array(['emotion', 'pixels', 'Usage'], dtype='<U9215')

In [ ]:
# first sample data
data[1]

array(['0',
       '70 80 82 72 58 58 60 63 54 58 60 48 89 115 121 119 115 110 98 91 84 84 90 99 110 126 143 153 158 171 169 172 169 165 129 110 113 107 95 79 66 62 56 57 61 52 43 41 65 61 58 57 56 69 75 70 65 56 54 105 146 154 151 151 155 155 150 147 147 148 152 158 164 172 177 182 186 189 188 190 188 180 167 116 95 103 97 77 72 62 55 58 54 56 52 44 50 43 54 64 63 71 68 64 52 66 119 156 161 164 163 164 167 168 170 174 175 176 178 179 183 187 190 195 197 198 197 198 195 191 190 145 86 100 90 65 57 60 54 51 41 49 56 47 38 44 63 55 46 52 54 55 83 138 157 158 165 168 172 171 173 176 179 179 180 182 185 187 189 189 192 197 200 199 196 198 200 198 197 177 91 87 96 58 58 59 51 42 37 41 47 45 37 35 36 30 41 47 59 94 141 159 161 161 164 170 171 172 176 178 179 182 183 183 187 189 192 192 194 195 200 200 199 199 200 201 197 193 111 71 108 69 55 61 51 42 43 56 54 44 24 29 31 45 61 72 100 136 150 159 163 162 163 170 172 171 174 177 177 180 187 186 187 189 192 192 194 195 196 197 199 200 201 200 1

### Working on labels

In [ ]:
labels = data[1:,0].astype(np.int8) # Converting the labels to numpy integer, because originally it was on string format

In [ ]:
labels

array([0, 0, 2, ..., 0, 3, 2], dtype=int8)

In [ ]:
np.unique(labels, return_counts=True) # Checking the number of counts in each categories

(array([0, 1, 2, 3, 4, 5, 6], dtype=int8),
 array([4953,  547, 5121, 8989, 6077, 4002, 6198]))

In [ ]:
# Mapping the integer labels to actual labels
key, values = np.unique(labels, return_counts=True)
for i in key:
  print(label_dictionary[i], values[i])

Angry 4953
Disgust 547
Fear 5121
Happy 8989
Sad 6077
Surprise 4002
Neutral 6198


### Working on image data

In [ ]:
from keras.preprocessing.image import img_to_array, array_to_img

In [ ]:
images = data[1:,1] # Except header (1:) --> Images pixel lies on second column(1).

In [ ]:
# Converting all the strings form of pixels into array
images = np.array([np.fromstring(image, np.uint8, sep=' ') for image in images])

In [ ]:
usage = data[1:, 2]
dataset = zip(labels, images, usage)

In [ ]:
np.unique(usage, return_counts=True) # Checking the number of data in training, publictest and privatetest dataset

(array(['PrivateTest', 'PublicTest', 'Training'], dtype='<U9215'),
 array([ 3589,  3589, 28709]))

In [ ]:
!ls "/content/drive/My Drive/ENGR635-Deep Learning System Design Project/Dataset/fer2013/"

fer2013.csv


In [ ]:
# This code block takes all the numpy array containing pixel information,
# converts to images, saves to respective categories of emotion, which are further 
# saved to Training, PublicTest, and PrivateTest folders
for i, d in enumerate(dataset):
    usage_path = os.path.join(d[-1],"")
    label_path = os.path.join(usage_path, label_names[d[0]])
    img = array_to_img(d[1].reshape((48, 48, 1)))
    img_name = '%d.png' % i
    img_path = os.path.join(label_path, img_name)
    if not os.path.exists(usage_path):
        os.mkdir(usage_path)
    if not os.path.exists(label_path):
        os.mkdir(label_path)
    img.save(img_path)
print("Completed !!!")

Completed !!!


In [ ]:
!ls # Checking current directory contents

drive  PrivateTest  PublicTest	sample_data  Training


In [ ]:
# Checking the number of images counts in Training directory
%%bash
root='Training/'
IFS=$(echo -en "\n\b")
(for dir in $(ls -1 "$root")
    do printf "$dir: " && ls -i "$root$dir" | wc -l
 done)

Angry: 3995
Disgust: 436
Fear: 4097
Happy: 7215
Neutral: 4965
Sad: 4830
Surprise: 3171


In [ ]:
# Checking the number of images counts in PublicTest directory
%%bash
root='PublicTest/'
IFS=$(echo -en "\n\b")
(for dir in $(ls -1 "$root")
    do printf "$dir: " && ls -i "$root$dir" | wc -l
 done)

Angry: 467
Disgust: 56
Fear: 496
Happy: 895
Neutral: 607
Sad: 653
Surprise: 415


In [ ]:
# Checking the number of images counts in PrivateTest directory
%%bash
root='PrivateTest/'
IFS=$(echo -en "\n\b")
(for dir in $(ls -1 "$root")
    do printf "$dir: " && ls -i "$root$dir" | wc -l
 done)

Angry: 491
Disgust: 55
Fear: 528
Happy: 879
Neutral: 626
Sad: 594
Surprise: 416


In [ ]:
# Zipping all the folders for saving it in drive
%%bash
(for dir in Training PublicTest PrivateTest
    do pushd $dir && zip -r $dir.zip * && popd
 done)

/content/Training /content
  adding: Angry/ (stored 0%)
  adding: Angry/19458.png (stored 0%)
  adding: Angry/18602.png (stored 0%)
  adding: Angry/21271.png (stored 0%)
  adding: Angry/2394.png (stored 0%)
  adding: Angry/14315.png (stored 0%)
  adding: Angry/16741.png (stored 0%)
  adding: Angry/8202.png (stored 0%)
  adding: Angry/8092.png (stored 0%)
  adding: Angry/13402.png (deflated 10%)
  adding: Angry/5295.png (stored 0%)
  adding: Angry/18889.png (stored 0%)
  adding: Angry/18022.png (stored 0%)
  adding: Angry/2108.png (stored 0%)
  adding: Angry/16761.png (stored 0%)
  adding: Angry/18001.png (stored 0%)
  adding: Angry/22647.png (stored 0%)
  adding: Angry/4229.png (stored 0%)
  adding: Angry/12237.png (stored 0%)
  adding: Angry/24902.png (stored 0%)
  adding: Angry/3564.png (stored 0%)
  adding: Angry/23793.png (stored 0%)
  adding: Angry/11158.png (stored 0%)
  adding: Angry/12543.png (stored 0%)
  adding: Angry/16657.png (stored 0%)
  adding: Angry/18343.png (stored 0%

In [ ]:
!ls

drive  PrivateTest  PublicTest	sample_data  Training


In [ ]:
ls -l Training/

total 55344
drwxr-xr-x 2 root root   131072 Oct 11 05:04 Angry/
drwxr-xr-x 2 root root    16384 Oct 11 05:04 Disgust/
drwxr-xr-x 2 root root   126976 Oct 11 05:04 Fear/
drwxr-xr-x 2 root root   204800 Oct 11 05:04 Happy/
drwxr-xr-x 2 root root   135168 Oct 11 05:04 Neutral/
drwxr-xr-x 2 root root   135168 Oct 11 05:04 Sad/
drwxr-xr-x 2 root root    81920 Oct 11 05:04 Surprise/
-rw-r--r-- 1 root root 55812330 Oct 11 05:05 Training.zip


In [ ]:
ls -l PublicTest/

total 6972
drwxr-xr-x 2 root root   20480 Oct 11 05:04 Angry/
drwxr-xr-x 2 root root    4096 Oct 11 05:04 Disgust/
drwxr-xr-x 2 root root   20480 Oct 11 05:04 Fear/
drwxr-xr-x 2 root root   36864 Oct 11 05:04 Happy/
drwxr-xr-x 2 root root   20480 Oct 11 05:04 Neutral/
-rw-r--r-- 1 root root 6992268 Oct 11 05:05 PublicTest.zip
drwxr-xr-x 2 root root   20480 Oct 11 05:04 Sad/
drwxr-xr-x 2 root root   16384 Oct 11 05:04 Surprise/


In [ ]:
ls -l PrivateTest/

total 6964
drwxr-xr-x 2 root root   20480 Oct 11 05:04 Angry/
drwxr-xr-x 2 root root    4096 Oct 11 05:04 Disgust/
drwxr-xr-x 2 root root   20480 Oct 11 05:04 Fear/
drwxr-xr-x 2 root root   32768 Oct 11 05:04 Happy/
drwxr-xr-x 2 root root   20480 Oct 11 05:04 Neutral/
-rw-r--r-- 1 root root 6989840 Oct 11 05:05 PrivateTest.zip
drwxr-xr-x 2 root root   20480 Oct 11 05:04 Sad/
drwxr-xr-x 2 root root   16384 Oct 11 05:04 Surprise/


In [ ]:
! ls {PrivateTest,PublicTest,Training}/*.zip

PrivateTest/PrivateTest.zip  PublicTest/PublicTest.zip	Training/Training.zip


In [ ]:
# Copying all the zipped files to drive folder for permanently saving for later use.
!cp {PrivateTest,PublicTest,Training}/*.zip '/content/drive/My Drive/ENGR635-Deep Learning System Design Project/Dataset/fer2013/'

In [ ]:
!ls '/content/drive/My Drive/ENGR635-Deep Learning System Design Project/Dataset/fer2013/'

fer2013.csv  PrivateTest.zip  PublicTest.zip  Training.zip
